ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true

    imu0: imu_data
    imu0_config: [false, false, false,
                   true, true, true,
                   true, false, false,
                   true, true, true,
                   true, true, true]
    imu0_differential: false
    imu0_relative: true
